select count(*) from dados_climaticos;
select min(data), max(data) from dados_climaticos;
select min(data), max(data) from dados_climaticos where estacao like '89004099999';
select min(data), max(data) from dados_climaticos where estacao like '87467099999';
select min(data), max(data) from dados_climaticos where estacao like '87468099999';
select min(data), max(data) from dados_climaticos where estacao like '87480099999';
select min(data), max(data) from dados_climaticos where estacao like '87497099999';
select min(data), max(data) from dados_climaticos where estacao like '87506099999';
select min(data), max(data) from dados_climaticos where estacao like '87509099999';
select min(data), max(data) from dados_climaticos where estacao like '87532099999';
select min(data), max(data) from dados_climaticos where estacao like '87534099999';
select min(data), max(data) from dados_climaticos where estacao like '87544099999';
select min(data), max(data) from dados_climaticos where estacao like '87548099999';
select min(data), max(data) from dados_climaticos where estacao like '87550099999';
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select count(*) from dados_climaticos;
select min(data), max(data) from dados_climaticos;
select min(data), max(data) from dados_climaticos where estacao like '89004099999';
select min(data), max(data) from dados_climaticos where estacao like '87467099999';
select min(data), max(data) from dados_climaticos where estacao like '87468099999';
select min(data), max(data) from dados_climaticos where estacao like '87480099999';
select min(data), max(data) from dados_climaticos where estacao like '87497099999';
select min(data), max(data) from dados_climaticos where estacao like '87506099999';
select min(data), max(data) from dados_climaticos where estacao like '87509099999';
select min(data), max(data) from dados_climaticos where estacao like '87532099999';
select min(data), max(data) from dados_climaticos where estacao like '87534099999';
select min(data), max(data) from dados_climaticos where estacao like '87544099999';
select min(data), max(data) from dados_climaticos where estacao like '87548099999';
select min(data), max(data) from dados_climaticos where estacao like '87550099999';
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 6;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 2;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 7;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 3;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 8;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 9;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 55;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 55;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 25;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 31;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select distinct(estacao) from dados_climaticos where temperatura_maxima >= 40;
select distinct(estacao) from dados_climaticos where temperatura_minima >= 25;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_maxima <= 5;
select distinct(estacao), nome, longitude, elevacao  from dados_climaticos where temperatura_minima <= 1;
select * from dados_climaticos where estacao = (select estacao from dados_climaticos where temperatura_maxima = (select max(temperatura_maxima) from dados_climaticos)) order by estacao, data desc;
select * from dados_climaticos where estacao = (select estacao from dados_climaticos where temperatura_minima = (select min(temperatura_minima) from dados_climaticos)) order by estacao, data desc;
select * from dados_climaticos where estacao = (select estacao from dados_climaticos where temperatura_maxima = (select min(temperatura_maxima) from dados_climaticos)) order by nome, data desc;
select * from dados_climaticos where estacao = (select estacao from dados_climaticos where temperatura_minima = (select max(temperatura_minima) from dados_climaticos)) order by nome, data desc;
